### ISSUE TITLE
Unable to install cellmodeller in mac or unix

### ISSUE THREAD

**Issue by pablo-guridi** [cellmodeller/CellModeller#23]
Hello, we are a group of students trying to install cellmodeller in mac and unix and we always get errors during the installation. See attached the document of the error we get when trying to install in mac or unix. In mac (error attached as .pdf), our version of python was 
3.7, so we thougth that could be the problem. Then we tried to install it in in unix both with python 3.7 and 2.7 and neither of them is working either (see also error text as .txt)

Thanks a lot in advance for your help!

[
[CellModeller_error_mac.pdf](https://github.com/HaseloffLab/CellModeller/files/4947918/CellModeller_error_mac.pdf)
[error_installing_unix.txt](https://github.com/HaseloffLab/CellModeller/files/4947919/error_installing_unix.txt)

](url)

**Comment by avimanyu786** [comment]
Hello @pablo-guridi @timrudge !

I've been working on a [docker container](https://hub.docker.com/r/avimanyu786/cellmodeller) based on the most recent version(4.3.1) and finally got it to work after several tweaks and modifications! 

It is based on an nvidia/opengl ubuntu 18.04 docker container..had to additionally set up several other prerequisites over it, such as OpenCL and Miniconda. After installing them, pip wasn't available once inside the cellmodeller environment and had to be additionally installed with `conda install pip`. Additional packages namely, `g++`, `libglib2.0.0` and `freeglut3-dev` were installed with `apt install` after building the Dockerfile and so I'd to use the `docker commit` command to update the image with the new changes in the container.

`g++` was required for `pip install -e .` to successfully install CellModeller.

For `python Scripts/CellModellerGUI.py`, the following packages and tweaks made it operable:

`libglib2.0.0` took care of the following issue:

`ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory`

I was then facing a plugin issue:

`Could not load the Qt platform plugin "xcb" in "" even though it was found.`

On installing `libqt5x11extras5`, that error went away but a new one came up:

`ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version Qt_5.15' not found required by....cellmodeller QtWidgets...`

After a lot of researching, I found out that it was happening because of the existing Qt 5.9 package within the container. After looking up the specific package name, I removed it: `apt remove libqt5core5a`.

This time CellModellerGUI.py was able to get past that error. But it again reported one final issue that was a `NullFunctionError` related to PyOpenGL.

Installing the package `freeglut3-dev` fixed it and then I was finally able to launch the GUI :+1: !

Removing the`libqt5core5a` package described above, also removed `libqt5x11extras5` but not the many dependencies that came along-with it(required for CellModeller to load correctly). So it is necessary to ignore the `apt autoremove` message reported by apt when running `apt update`.

With this new container, deployment should no longer be much of an issue. Please see https://github.com/avimanyu786/cellmodeller-docker for step by step instructions on the same. Hope it helps :) !
