### ISSUE TITLE
Not able to install on Mac

### ISSUE THREAD

**Issue by YMVio** [cellmodeller/CellModeller#25]
Hello there,

I'm new to programming but want to self-learn CellModeller. However it seems it didn't install successfully in my terminal.
It looks like this:

1. Installing CellModeller and dependencies via Anaconda...
------------------------------------------------------------

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Applications/anaconda3/envs/cellmodeller

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate cellmodeller
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: 

usage: dirname path

2. Setting up user environment in /Users/YM/cellmodeller...
-------------------------------------------------------

cp: /PackageFiles/Scripts: No such file or directory
cp: /Users/YM/Pictures: unable to copy extended attributes to 1/cellmodeller/YM/Pictures: Permission denied
cp: /Users/YM/Pictures: Permission denied
cp: /Users/YM/Library: unable to copy extended attributes to 1/cellmodeller/YM/Library: Permission denied
cp: /Users/YM/Library: Permission denied
cp: /PackageFiles/Doc: No such file or directory
cp: /Users/YM/Pictures: unable to copy extended attributes to 1/cellmodeller/YM/Pictures: Permission denied
cp: /Users/YM/Pictures: Permission denied
cp: /Users/YM/Library: unable to copy extended attributes to 1/cellmodeller/YM/Library: Permission denied
cp: /Users/YM/Library: Permission denied
cp: /PackageFiles/Examples: No such file or directory
cp: /Users/YM/Pictures: unable to copy extended attributes to 1/cellmodeller/YM/Pictures: Permission denied
cp: /Users/YM/Pictures: Permission denied
cp: /Users/YM/Library: unable to copy extended attributes to 1/cellmodeller/YM/Library: Permission denied
cp: /Users/YM/Library: Permission denied
cp: /PackageFiles/cmgui: No such file or directory
cp: /Users/YM is a directory (not copied).
cp: /PackageFiles/cmpython: No such file or directory
cp: /Users/YM is a directory (not copied).

3. Adding paths to bash_profile
-------------------------------------------------------

touch: /Users/YM: Permission denied
touch: /Users/YM: Permission denied
/Users/YM 1/Downloads/InstallCellModeller-v4.3-OSX/InstallCellModeller: line 73: $HOME/.bash_profile: ambiguous redirect
/Users/YM 1/Downloads/InstallCellModeller-v4.3-OSX/InstallCellModeller: line 74: $HOME/.bash_profile: ambiguous redirect
/Users/YM 1/Downloads/InstallCellModeller-v4.3-OSX/InstallCellModeller: line 75: $HOME/.bashrc: ambiguous redirect
/Users/YM 1/Downloads/InstallCellModeller-v4.3-OSX/InstallCellModeller: line 76: $HOME/.bashrc: ambiguous redirect
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

And then command "cmgui" cannot be found.

Looking forward to your response.

**Comment by avimanyu786** [comment]
Hi @YMVio,

You can try this [image](https://hub.docker.com/r/avimanyu786/cellmodeller) with [Docker on Mac](https://hub.docker.com/editions/community/docker-ce-desktop-mac/).

Since you're on Mac, the appropriate modifications as per this [reference](https://techsparx.com/software-development/docker/display-x11-apps.html) would be necessary as the documentation provided with the image is for Linux. However, on Docker, you would still require connecting to a Linux host for [GPU support](https://github.com/NVIDIA/nvidia-docker/issues/758#issuecomment-396648199) .

**Comment by avimanyu786** [comment]
Hi @YMVio,

You are getting "Permission denied" errors since the CellModeller OSX installer shell script perhaps does not have executable permissions on your user account. It seems to be located under `/Users/YM 1/Downloads/`. Try placing it within the `YM` folder instead of `YM 1`. Please check this [link](https://www.quora.com/Why-do-I-get-a-permission-denied-message-when-I-install-Anaconda-2-4-4-0-on-the-Mac) for more details and workarounds on the error.

You can also try this [container image](https://hub.docker.com/r/avimanyu786/cellmodeller) with [Docker on Mac](https://hub.docker.com/editions/community/docker-ce-desktop-mac/).

Since you're on Mac, the appropriate modifications as per this [reference](https://techsparx.com/software-development/docker/display-x11-apps.html) would be necessary as the documentation provided with the image is for Linux. However, on Docker for Mac, you would still require connecting to a Linux host for [GPU support](https://github.com/NVIDIA/nvidia-docker/issues/758#issuecomment-396648199) .

**Comment by avimanyu786** [comment]
Hi @YMVio,

You are getting "Permission denied" errors since the CellModeller OSX installer shell script perhaps does not have executable permissions on your user account. It seems to be located under `/Users/YM 1/Downloads/`. Try placing it within the `YM` folder instead of `YM 1`. Please check this [link](https://www.quora.com/Why-do-I-get-a-permission-denied-message-when-I-install-Anaconda-2-4-4-0-on-the-Mac) for more details and workarounds on the error.

You can also try this [container image](https://hub.docker.com/r/avimanyu786/cellmodeller) with [Docker on Mac](https://hub.docker.com/editions/community/docker-ce-desktop-mac/). Since you're on Mac, the appropriate modifications as per this [reference](https://techsparx.com/software-development/docker/display-x11-apps.html) would be necessary as the documentation provided with the image is for Linux. However, on Docker for Mac, you would still require connecting to a Linux host for [GPU support](https://github.com/NVIDIA/nvidia-docker/issues/758#issuecomment-396648199) .

**Comment by timrudge** [comment]
Hi - the installer is out of date and needs to be updated. I recommend that you switch to our python 3 version which is currently on a development branch awaiting release soon. In the meantime, here are instructions to set it up (make sure you are using python 3). 

1. Clone the repo: git clone https://github.com/HaseloffLab/CellModeller.git
2. cd CellModeller
3. Switch to new branch: git checkout python3
4. pip install -e .

Now you can run the GUI as “python Scripts/CellModellerGUI.py"

Let me know any problems.

Tim
